In [ ]:
!python infix_prefix.py

In [ ]:
# install sympy

In [ ]:
from sympy import *

In [ ]:
!python random_unary_binary_tree.py

In [ ]:
!python infix_prefix.py

In [ ]:
str(simplify(sympify("log(exp(x))")))

In [ ]:
!python infix_prefix2.py

In [ ]:
thisset = set(["2", "3"])
for e in thisset:
    print(thisset)

In [ ]:
from  random_unary_binary_tree1 import random_binary_trees
import time

In [ ]:
n = 12
start = time.time()
root = random_binary_trees(n)
time1 = time.time()
print("Generate tree:", time1 - start)

In [ ]:
n = 15
start = time.time()
root = random_binary_trees(n)
time1 = time.time()
print("Generate tree:", time1 - start)

In [ ]:
p_leaf = [1/6, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12]

In [ ]:
sum(p_leaf)

In [ ]:
import numpy as np

In [ ]:
np.array(["x", "-5", "-4", "-3", "-2", "-1", "1", "2", "3", "4", "5"])

In [ ]:
import numpy as np 
  
a = np.array(["hello world"]) 
  
print("type is: ",type(a)) 
print("dtype is: ",a.dtype)

In [ ]:
from sympy import *

In [ ]:
sympify("log(2)")

In [ ]:
from sympy.parsing.sympy_parser import parse_expr

In [ ]:
parse_expr("log(2)")

In [ ]:
file = open(r"test.txt", "w+")
for i in range(5):
    string = str(i) + "\n"
    file.writelines(string) 

In [ ]:
sequence = []

start = time.time()

i = 1
while i<=10:
    n = random.randint(1, 15)
    print(n)
    root = random_binary_trees(n)
    print("generated")
    result = traverse_unary_binary_prefix(root)
    if 'x' not in result:
        continue
    print("prefix:", result)    
    result_infix = prefix_to_infix(result) 
    result_expr = " ".join(result_infix)
    result_expr = parse_expr_timeout(result_expr)
    if result_expr==None:
        continue
    result_simp = simplify_timeout(result_expr)
    if result_simp == "Error":
        continue
    print("infix:", result_simp)
    result_simp_prefix = infix_to_prefix(result_simp)
    if result_simp_prefix == False:
        continue
    print("pass 1") 
    try:
        expr_diff = diff(result_simp)
    except ValueError:
        continue
    #print(expr_diff)
    expression = simplify_timeout(expr_diff)
    print("expression infix:", expression)
    expression_prefix = infix_to_prefix(expression)
    if expression_prefix == False:
        continue
    print("expression prefix:", expression_prefix)    
    expression_prefix = " ".join(expression_prefix)
    result_simp_prefix = " ".join(result_simp_prefix)
    sequence.append(expression_prefix + "\t" + result_simp_prefix + "\n")
    print("added")
    i += 1
    
end = time.time()
print(end - start)  

In [ ]:
import numpy as np

In [ ]:
np.newaxis

In [ ]:
np.arange(10)[:, np.newaxis]

In [ ]:
np.arange(10)

In [ ]:
np.arange(10)[:]

In [ ]:
np.arange(10)[np.newaxis, :]

In [ ]:
import tensorflow as tf

In [ ]:
a1 = tf.constant([], shape=(2, 3))
a2 = tf.ones((2, 3))
tf.concat([a2], axis=0)

In [ ]:
def encoder_layer(input_layer, num_heads, layer, training):
    #multi-head self attention 
    for i in range(num_heads):
        q_i = layers.Dense(depth, name="layer" + str(layer) + "_" + "en_query" + str(i))(input_layer)
        k_i = layers.Dense(depth, name="layer" + str(layer) + "_" + "en_key" + str(i))(input_layer)
        v_i = layers.Dense(depth, name="layer" + str(layer) + "_" + "en_value" + str(i))(input_layer)
        self_attention_i = layers.Attention(
            use_scale=True,
            name = "layer" + str(layer) + "_" + "en_self_attention" + str(i),
            )([q_i, v_i, k_i])
        if i == 0:
            concat_attention = tf.concat([self_attention_i], axis=2)
        else:
            concat_attention = tf.concat([concat_attention, self_attention_i], axis=2)      
    self_attention = layers.Dense(d_model, name="layer" + str(layer) + "_" + "en_concat_attention")(concat_attention)
    self_attenton = layers.Dropout(rate=0.1)(self_attention, training=training)
    
    #layer norm1
    layernorm1 = layers.LayerNormalization(epsilon=1e-6, name="layer" + str(layer) + "_" + "en_layer_norm1")(self_attention + input_layer)
    
    # feed forward
    ffn1 = tf.keras.layers.Dense(dff, activation='relu')(layernorm1)
    ffn2 = tf.keras.layers.Dense(d_model, name="layer" + str(layer) + "_" + "en_feed_forward")(ffn1)
    ffn2 = layers.Dropout(rate=0.1)(ffn2, training=training)
    
    #layer norm2
    layernorm2 = layers.LayerNormalization(epsilon=1e-6, name="layer" + str(layer) + "_" + "en_layer_norm2")(ffn2+layernorm1)
    return layernorm2
    

In [4]:
import sympy

In [5]:
from sympy import *

In [6]:
x = Symbol('x', real=True)

In [7]:
import ray
from ray.exceptions import RayTimeoutError

In [10]:
ray.shutdown()
ray.init()
def simplify_timeout(expr):
 
    result = None
    
    @ray.remote
    def f(expr):
        try:
            return simplify(expr)
        except:
             return "Error"

    obj_id = f.remote(expr)
    try:
        return ray.get(obj_id, timeout=3)
    except RayTimeoutError:
        return None

2020-03-19 15:02:46,102	INFO resource_spec.py:212 -- Starting Ray with 5.42 GiB memory available for workers and up to 2.72 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-03-19 15:02:46,354	INFO services.py:1078 -- View the Ray dashboard at localhost:8265


In [11]:
print(simplify_timeout(1+x+x**2+log(tanh(x)+4)))
print(simplify_timeout(1+x+x**2+log(tanh(x)+4)))

x**2 + x + log(tanh(x) + 4) + 1
x**2 + x + log(tanh(x) + 4) + 1


In [23]:
str(type(AccumBounds(0, 2)))

"<class 'sympy.calculus.util.AccumulationBounds'>"

In [2]:
import tensorflow as tf

In [3]:
def create_look_ahead_mask(size):
  mask = 1 - tf.linalg.band_part(tf.ones((size, size)), -1, 0)
  return mask  # (seq_len, seq_len)

In [4]:
x = tf.random.uniform((1, 3))
temp = create_look_ahead_mask(x.shape[1])
print(x)
print(temp)

tf.Tensor([[0.29833364 0.39729702 0.45133793]], shape=(1, 3), dtype=float32)
tf.Tensor(
[[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [5]:
-1e9

-1000000000.0

In [6]:
from tensorflow.python.ops import math_ops

In [13]:
padding_mask = math_ops.logical_not(tf.constant([False, False, True]))

In [14]:
from tensorflow.python.keras import backend as K

In [15]:
math_ops.cast(padding_mask, dtype=K.floatx())

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 0.], dtype=float32)>

In [1]:
import tensorflow as tf

In [24]:
def create_look_ahead_mask2(size):
    mask = tf.linalg.band_part(tf.ones((size, size)), -1, 0)
    #mask = tf.cast(mask, tf.int32)
    mask = tf.cast(mask, tf.bool)
    return mask 

In [48]:
x = tf.random.uniform((1, 3))
print(x.shape)
temp = create_look_ahead_mask(x.shape[1])
print(temp.shape)
temp2 = create_look_ahead_mask2(x.shape[1])
print(temp2.shape)

(1, 3)
(3, 3)
(3, 3)


In [2]:
def create_padding_mask(seq):
    seq = tf. cast(1 - tf.cast(tf.math.equal(seq, 0), tf.int32), tf.bool)
  
    return seq

In [3]:
x = tf.constant([[7, 6, 0, 0, 1], [1, 2, 3, 0, 0], [0, 0, 0, 4, 5]])
y = create_padding_mask(x)

In [5]:
print(x)
print(y)

tf.Tensor(
[[7 6 0 0 1]
 [1 2 3 0 0]
 [0 0 0 4 5]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[ True  True False False  True]
 [ True  True  True False False]
 [False False False  True  True]], shape=(3, 5), dtype=bool)


In [46]:
from tensorflow.python.ops import array_ops

In [47]:
z = array_ops.expand_dims(y, axis=-2)
print(z.shape)

(3, 1, 5)


In [49]:
zz = array_ops.expand_dims(temp2, axis=-2)
print(zz)

tf.Tensor(
[[[ True False False]]

 [[ True  True False]]

 [[ True  True  True]]], shape=(3, 1, 3), dtype=bool)


In [50]:
print(temp2)

tf.Tensor(
[[ True False False]
 [ True  True False]
 [ True  True  True]], shape=(3, 3), dtype=bool)


In [1]:
import ray

In [2]:
l = []
l.append(l)

# Try to put this list that recursively contains itself in the object store.
ray.put(l)


RayConnectionError: Ray has not been started yet. You can start Ray with 'ray.init()'.

In [4]:
ray.shutdown()
ray.init()

class Foo(object):
    def __init__(self, value):
        self.value = []
        self.value = self.value.append(value)

def custom_serializer(obj):
    return obj.value

def custom_deserializer(value):
    object = Foo(value)
   # object.value = value
    return object

ray.register_custom_serializer(Foo, serializer=custom_serializer, deserializer=custom_deserializer)

object_id = ray.put(Foo(100))
print(ray.get(object_id).value) 

2020-03-21 10:02:07,183	INFO resource_spec.py:212 -- Starting Ray with 4.88 GiB memory available for workers and up to 2.45 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-03-21 10:02:07,426	INFO services.py:1123 -- View the Ray dashboard at localhost:8265


None


In [1]:
ls dataset | wc -l

   29045


In [1]:
import tensorflow as tf

In [31]:
list_ds1 = tf.data.Dataset.list_files("./data_generation/*.txt", shuffle=None, seed=None) 
list_ds2 = tf.data.Dataset.list_files("./dataset/*.txt", shuffle=None, seed=None) 

In [32]:
list_ds = list_ds1.concatenate(list_ds2) 

In [37]:
for f in list_ds.take(5):
  print(f.numpy())

b'./data_generation/bwd800_18.txt'
b'./data_generation/bwd800_46.txt'
b'./data_generation/bwd800_47.txt'
b'./data_generation/bwd800_85.txt'
b'./data_generation/bwd800_90.txt'


In [81]:
def process_path(file_path):
    line = tf.io.read_file(file_path)
    line1 = tf.strings.split(line, sep='\n')
    line2 = tf.strings.split(line1, sep='\t')
    return line2

In [92]:
lines = list_ds2.map(process_path)

In [93]:
lines

<MapDataset shapes: (None, None), types: tf.string>

In [94]:
num_elements = tf.data.experimental.cardinality(lines).numpy()

In [95]:
num_elements

29045

In [89]:
# for line in lines.take(2):
#     print(line)

In [40]:
lines = tf.io.read_file(b'./data_generation/bwd800_18.txt')

In [25]:
dataset_test = tf.data.TextLineDataset("./data_generation/bwd800_0.txt") 

In [27]:
for line in dataset_test.take(5):
  print(line.numpy())

b'* 72 * pow + 63 * 8 * x + * -3 exp 1 * 2 x -2 + -63 * 16 pow x 2\t+ -4 * -3 pow + * -1 exp 1 + * / 2 3 x * / 21 8 pow x -1 -1'
b'* -4 * pow x -1 * pow + -25 * 4 pow + log x sin 3 2 / -1 2 pow acosh + * / -2 5 log x * / -2 5 sin 3 -2\t+ -5 * -2 pow acosh + * / -2 5 log x * / -2 5 sin 3 -1'
b'0\t+ 5 exp * 4 pow + 2 * -1 asin 2 -1'
b'* pow cos x -2 acosh + * / 1 2 atanh 3 * / -1 2 tanh 3\t* + -3 tan x acosh + * / 1 2 atanh 3 * / -1 2 tanh 3'
b'* 2 * pow + 1 * -1 pow + * -1 tan + 1 * -1 tan 4 tan + * / 5 2 x asinh 3 2 / -1 2 + / 5 2 * / 5 2 pow tan + * / 5 2 x asinh 3 2\t+ -3 * -2 acos + * -1 tan + 1 * -1 tan 4 tan + * / 5 2 x asinh 3'


In [106]:
import os
file_list = os.listdir("./data/dataset")


In [108]:
file_list = [os.path.join(".", "data", "dataset", path) for path in file_list]

In [110]:
len(file_list)

30466

In [1]:
import tensorflow as tf

In [6]:
a = ['a', 'b', 'a']
b = [0, 1, 0]
c = 

TypeError: list indices must be integers or slices, not list

In [7]:
import pandas as pd

In [ ]:
pd.DataFrame

In [10]:
a = []
b =[['c']]
a.extend(b)

In [11]:
a

[['c']]

In [ ]:
!python generate_dataset.py --cpu 8 --num 256 --n 8

In [ ]:
ls data/dataset | wc -l

In [ ]:
pip install -U ray-0.9.0.dev0-cp36-cp36m-macosx_10_13_intel.whl

In [52]:
from math import log
from numpy import array
from numpy import argmax
 
# beam search
def beam_search_decoder(data, k):
	sequences = [[list(), 1.0]]
	# walk over each step in sequence
	for row in data:       
		all_candidates = list()
		# expand each current candidate
		for i in range(len(sequences)):
			seq, score = sequences[i]           
			for j in range(len(row)):
				candidate = [seq + [j], score * -log(row[j])]
				all_candidates.append(candidate)           
		# order all candidates by score
		ordered = sorted(all_candidates, key=lambda tup:tup[1])
		# select k best
		sequences = ordered[:k]
	return sequences
 
# define a sequence of 10 words over a vocab of 5 words
data = [[0.1, 0.2, 0.3, 0.4, 0.5],
		[0.5, 0.4, 0.3, 0.2, 0.1],
		[0.1, 0.2, 0.3, 0.4, 0.5],
		[0.5, 0.4, 0.3, 0.2, 0.1],
		[0.1, 0.2, 0.3, 0.4, 0.5],
		[0.5, 0.4, 0.3, 0.2, 0.1],
		[0.1, 0.2, 0.3, 0.4, 0.5],
		[0.5, 0.4, 0.3, 0.2, 0.1],
		[0.1, 0.2, 0.3, 0.4, 0.5],
		[0.5, 0.4, 0.3, 0.2, 0.1]]
data = array(data)
# decode sequence
result = beam_search_decoder(data, 3)
#print result
for seq in result:
	print(seq)

[[4, 0, 4, 0, 4, 0, 4, 0, 4, 0], 0.025600863289563108]
[[4, 0, 4, 0, 4, 0, 4, 0, 4, 1], 0.03384250043584397]
[[4, 0, 4, 0, 4, 0, 4, 0, 3, 0], 0.03384250043584397]


In [2]:
i = 0
for row in data:
    i +=1
print(i)    

10


In [44]:
import tensorflow as tf

In [46]:
from tensorflow.keras import backend as K

In [25]:
import numpy as np

In [87]:
data1 = np.expand_dims(np.expand_dims(data[0], axis=0), axis=0)

In [88]:
data1.shape

(1, 1, 5)

In [85]:
data.shape

(10, 5)

In [89]:
tf.keras.backend.ctc_decode(data1, input_length=np.ones(data1.shape[0])*data1.shape[1], greedy=True)

([<tf.Tensor: shape=(1, 0), dtype=int64, numpy=array([], shape=(1, 0), dtype=int64)>],
 <tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[0.69314698]])>)

In [90]:
K.get_value(tf.keras.backend.ctc_decode(data1, input_length=np.ones(data1.shape[0])*data1.shape[1], greedy=True)[0][0])

array([], shape=(1, 0), dtype=int64)

In [91]:
np.ones(data1.shape[0])*data1.shape[1]

array([1.])

In [92]:
input_length=np.ones(data1.shape[0])*data1.shape[2]

In [93]:
input_length

array([5.])

In [94]:
tf.keras.backend.ctc_decode(data1, input_length=np.ones(data1.shape[0])*data1.shape[1], greedy=False, beam_width=3, top_paths=3)

([<tf.Tensor: shape=(1, 0), dtype=int64, numpy=array([], shape=(1, 0), dtype=int64)>,
  <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[3]])>,
  <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[2]])>],
 <tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[-1.09861242, -1.32175592, -1.60943791]])>)

In [98]:
tf.keras.backend.ctc_decode(data, input_length=(data.shape[0], ), greedy=False, beam_width=4, top_paths=4)

InvalidArgumentError: transpose expects a vector of size 2. But input(1) is a vector of size 3 [Op:Transpose] name: transpose/